### PR TITLE
Fixes #26 Brush moves erroneously when set to non-one scale.

### LINKED ISSUE #26: Brush moves erroneously when set to non-one scale
Great addon!  I've been using it for a bit, but ran into something today that caused a lot of head scratching until I finally figured out what I had done wrong.  Every time I grabbed a few brushes to move them with the resize bounds tool, they moved both faces on the edited axis to an unexpected position.

# Repro steps:
1. Click cube to place a cube.  
2. Set scale to 5, 5, 5
3. Grab bounds resize handles -- now moving the brush causes it to re-center

# Suggestion:
If non-one scale is not supported, then could just display a warning to user when they attempt to set a non-one scale and reset it back to a proper value.

### PR DESCRIPTION
**Pull request by Henry00IS**
I can't recommend scaling brushes like this but at least this stops random re-positioning for any users that do so regardless.

The transformation controls (and visual bounds) are scaling properly, be it the root "CSGModel" or compound brushes. However, their child brushes' built geometry does not scale relative to the parent. If we can add support for that we'd probably support scaling completely and can thus also fix issue #23.

### CODE REVIEW

File: Scripts/Brushes/PrimitiveBrush.cs [hunk 1]
```diff
@@ -817,7 +817,7 @@ public void ResetPivot()
 			}
 
 			// Bounds is aligned with the object
-			transform.Translate(delta);
+			transform.Translate(delta.Multiply(transform.localScale));
```
Comment (sabresaurus) [inline Scripts/Brushes/PrimitiveBrush.cs]: Conceivably this could be lossyScale, but that may have issues if the brush is rotated and the parent/root is scaled non-uniformly

Comment (Henry00IS) [reply Scripts/Brushes/PrimitiveBrush.cs]: I had the same thoughts and lossyScale worked just fine on my quick tests however like I mentioned the parent/root scaling is ignored by the CSG building process (the tools and wire-frames scale properly), it's not ignored for brushes where it works perfectly but it's ignored again for compound brushes (another parent scale I suppose). LossyScale did not resolve this problem in any way or form. It would be nice to fix all of the scaling. But unless you immediately know where to look to change the CSG output to scale according to the parents...?
